name: ArrivalDetection
language: python
variables:
  - name: LiveTrainData
    inputType: InputTopic
    description: Receives the progress of the trains that are currently moving
    required: false
  - name: output
    inputType: ArrivalTrainData
    description: Sends the data from trains that are close to their destination
    defaultValue: transform
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
