name: ArrivalDetection
language: python
variables:
  - name: LiveTrainData
    inputType: InputTopic
    description: Receives the progress of the trains that are currently moving
    defaultValue: LiveTrainData
    required: false
  - name: ArrivalTrainData
    inputType: OutputTopic
    description: Sends the data from trains that are close to their destination
    defaultValue: ArrivalTrainData
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
