name: Live Train Data Generator
language: python
variables:
  - name: LiveTrainData
    inputType: InputTopic
    description: Sends the progress of the trains that are currently moving
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
