name: Live Train Data Generator
language: python
variables:
  - name: ArrivalTrainData
    inputType: InputTopic
    description: Sends the data from trains that are close to their destination
    defaultValue: ArrivalTrainData
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
